imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        email_manager: "@email_manager"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [KijhoMailerBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            
fkr_css_url_rewrite:
    rewrite_only_if_file_exists: true
    clear_urls: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
#swiftmailer:
#    transport: "%mailer_transport%"
#    host:      "%mailer_host%"
#    username:  "%mailer_user%"
#    password:  "%mailer_password%"
#    spool:     { type: memory }

swiftmailer:
    default_mailer: first_mailer
    mailers:
        first_mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool:     { type: memory }
        second_mailer:
            transport: "%mailer_transport_second%"
            host:      "%mailer_host_second%"
            username:  "%mailer_user_second%"
            password:  "%mailer_password_second%"
            spool:     { type: memory }
    
    
kijho_mailer:
    entity_directories: ["%kernel.root_dir%/../src/Kijho/MailerBundle/Entity/"]
    entity_namespace: "Kijho\MailerBundle\Entity"
    storage:
        layout:         "Kijho\MailerBundle\Entity\EmailLayout"
        template_group: "Kijho\MailerBundle\Entity\EmailTemplateGroup"
        template:       "Kijho\MailerBundle\Entity\EmailTemplate"
        settings:       "Kijho\MailerBundle\Entity\EmailSettings"
        email:          "Kijho\MailerBundle\Entity\Email"
        email_event:    "Kijho\MailerBundle\Entity\EmailEvent"
        
services:
    twig.extension.evaluate:
      class: Twig\Extension\EvaluateExtension
      tags:
          - { name: twig.extension }  
